config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'main#home'
  resources :categories
  
  get '/transaction', to: 'transactions#index', as: 'transaction'
  get '/transaction/:category_id', to: 'transactions#index', as: 'transaction_category'
  get '/transactions/new/:category_id', to: 'transactions#new', as: 'new_transaction'
  post '/transactions', to: 'transactions#create', as: 'create_transaction'
  resources :transactions, only: [:index, :new, :create]
  get '/main/home', to: 'main#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :transactions
  belongs_to :user
  attribute :created_at, :datetime
  has_one_attached :image
  validates :name, presence: true
  validates :image, presence: true
  has_and_belongs_to_many :purchases, dependent: :destroy
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :category
  validates :transaction_name, presence: true
  validates :transaction_price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories
  attr_accessor :name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_active_storage_url_options, only: %i[index show]

  def index
    @categories = current_user.categories.order(:id)
    @category_totals = {}

    @categories.each do |category|
      total_price = category.transactions.sum(:transaction_price)
      @category_totals[category.id] = total_price
    end
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end

  def create
    @category = current_user.categories.build(category_params)

    if @category.save
      redirect_to root_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  private

  def set_active_storage_url_options
    ActiveStorage::Current.url_options = url_options
  end

  def category_params
    params.require(:category).permit(:name, :image, :created_at)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    @categories = Category.all.order(:id)
    render 'main/home'
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @transactions = @category.transactions
    @total_price = @transactions.sum(:transaction_price)
  end

  def new
    @category = Category.find(params[:category_id])
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)
    if @transaction.save
      redirect_to transaction_category_path(@transaction.category_id), notice: 'Transaction created successfully.'
    else
      render :new
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:transaction_name, :transaction_price, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/_cat_list.html.erb
<nav class="CatNav">
  <p class="CatNavLines">|||</p>
  <p class="CatNavHeading">CATEGORIES</p>
  <%= button_to "Bye", destroy_user_session_path, method: :delete, class: 'SignOut' %>
</nav>

<div class="CatList">
  <% @categories.each do |category| %>
    <% next unless category.user_id == current_user&.id %>
    <% total_price = category.transactions.sum(:transaction_price) %>
    <div class="CatContent" onclick="window.location.href='/transaction?category_id=<%= category.id %>';">
      <div class="ImgDiv">
        <% if category.image.present? %>
          <img src="<%= url_for(category.image) %>">
        <% else %>
          <!-- Placeholder image if no image is present -->
          <img src="/assets/placeholder_image.jpg">
        <% end %>
      </div>
      <div class="CatDesc">
        <div class="CatTitle">
          <%= category.name %>
        </div>
        <div class="CatDate">
          <%= category.created_at&.strftime("%d %b %Y") %>
        </div>
      </div>
      <div class="CatPrice">$<%= total_price %></div>
    </div>
  <% end %>
</div>

<div class="CatFoot">
  <%= link_to "Add new Category", new_category_path, class: "AddCatButton" %>
</div>

app/views/categories/index.html.erb
<!-- app/views/categories/index.html.erb -->

<div class="CatList">
  <% @categories.each do |category| %>
    <div class="CatContent">
      <div class="ImgDiv">
        <img src="<%= category.image.url %>">
      </div>
      <div class="CatDesc">
        <div class="CatTitle">
          <%= category.name %>
        </div>
        <div class="CatDate">
          <%= category.created_at.strftime("%d %b %Y") %>
        </div>
      </div>
      <div class="CatPrice">$150.0</div>
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<nav class="ACatNav">
  <p class="ACatNavLines">
  <%= link_to "<", root_path %>
  </p>
  <p class='ACatNavHeading'>ADD CATEGORIES</p>
  <%= button_to "Bye", destroy_user_session_path, method: :delete, class: 'ASignOut' %>
</nav>

<%= form_for @category, url: categories_path, html: { class: "SignUpPage" } do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="CatCreateField">
    <%= f.label :name, class: "CatLabel" %><br>
    <%= f.text_field :name, autofocus: true, class: "CatInput" %>
  </div>

  <div class="CatField">
    <%= f.label :image, class: "CatLabel" %><br>
    <%= f.file_field :image, class: "CatInput" %>
  </div>

  <%= f.hidden_field :created_at, value: Time.current %>

  <div class="CatActions">
    <%= f.submit "Save", class: "CatButton" %>
  </div>
<% end %>

app/views/layouts/_loginpage.html.erb
<section class="LoginPage">
  <div class="LoginSplash">
    <ul class="LoginUl">
      <% unless controller_name == 'registrations' || controller_name == 'sessions' %>
        <% if current_user %>
        <% else %>
          <li class="LoginLi Glow"> <%= link_to "Log In", new_user_session_path %></li>
          <li class="LoginLi"> <%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wealtho</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if current_user %>
      <%= yield %>
      <%= render 'layouts/loginpage' %>
    <% else %>
    <%= yield %>
      <%= render 'layouts/loginpage' %>
    <% end %>
  </body>
</html>

app/views/main/home.html.erb
<section class="Homepage">
  <% unless current_user %>
    <h1 class="LoginLogo">WealthO</h1>
  <% end %>
  <% if current_user %>
    <%= render partial: 'categories/cat_list', locals: { categories: @categories } %>
  <% end %>
</section>

app/views/transactions/index.html.erb
<nav class="TranNav">
<p class="ACatNavLines">
<%= link_to "<", root_path %>
</p>
<p class='CatNavHeading'>Transaction</p>
<%= button_to "Bye", destroy_user_session_path, method: :delete, class: 'SignOut' %>
</nav>

<div class="CatContent">
<div class="ImgDiv">
<% if @category.image.present? %>
  <img src="<%= url_for(@category.image) %>">
<% else %>
  <!-- Placeholder image if no image is present -->
  <img src="/assets/placeholder_image.jpg">
<% end %>
</div>
  <div class="TranDesc">
    <div class="TranTitle">
      <%= @category.name %>
    </div>
  </div>
  <div class="TranPrice">$<%= @total_price %></div>
</div>

<% if @category.transactions.present? %>
  <% @category.transactions.each do |transaction| %>
    <div class="NewTranContent">
      <div class="NewTranDesc">
        <div class="NewTranTitle">
          <%= transaction.transaction_name.present? ? transaction.transaction_name : 'No values' %>
        </div>
        <div class="CatDate">
        <%= @category.updated_at&.strftime("%d %b %Y") %>
        </div>
      </div>
      <div class="NewTranPrice">
        <%= transaction.transaction_price.present? ? "$#{transaction.transaction_price}" : 'No values' %>
      </div>
    </div>
  <% end %>
<% else %>
  <p>No transactions found.</p>
<% end %>

<div class="CatFoot">
  <%= link_to "Add new Transaction", new_transaction_path(category_id: @category.id), class: "AddCatButton" %>
</div>

app/views/transactions/new.html.erb
<nav class="CatNav">
<p class="ACatNavLines">
<%= link_to "<", transaction_path(category_id: @category.id) %>
</p>
<p class='CatNavHeading'>New Transaction</p>
<%= button_to "Bye", destroy_user_session_path, method: :delete, class: 'SignOut' %>
</nav>

<%= form_for @transaction, url: create_transaction_path do |f| %>
  <%= f.hidden_field :category_id, value: @category.id %>
  <%= f.hidden_field :updated_at, value: Time.current %>

  <div class="ATranName">
  <%= f.label :Name %><br>
  <%= f.text_field :transaction_name, autofocus: true, placeholder: 'Enter transaction name' %>
</div>

<div class="ATranPrice">
  <%= f.label :Price %><br>
  <%= f.number_field :transaction_price, placeholder: 'Enter transaction price' %>
</div>


  <div class="ATranCat">
  <%= f.label :Groups %><br>
  <p class="ATranCatName"><%= @category.name %></p>
</div>

  <div class="ATranCreate">
    <%= f.submit "Create Transaction" %>
  </div>
<% end %>